version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "Main"
          ContainerPort: 80
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - "subnet-0f0cc77a0917218df"
              - "subnet-049d00413aecc1d15"
            SecurityGroups:
              - "sg-03d8e6b8acaf01224"
            AssignPublicIp: "ENABLED"
